---
- name: Install bearded-avenger with elasticsearch (using Docker)
  hosts: localhost
  become: True
  roles:
    - { role: ubuntu14, tags: role-ubuntu14 }
    - { role: elasticsearch, tags: role-elasticsearch }
    - { role: bearded-avenger, tags: role-bearded-avenger }

  post_tasks:

    - name: start cif-services
      command: service cif-services start
