---
- name: Install bearded-avenger with elasticsearch (using Docker)
  hosts: localhost
  become: True
  vars:
    - cif_store_store: 'elasticsearch'

  roles:
    - { role: ubuntu14, tags: role-ubuntu14 }
    - { role: elasticsearch, tags: role-elasticsearch }
    - { role: bearded-avenger, tags: role-bearded-avenger }

  post_tasks:
    - name: enable services at boot
      service: name={{ item }} enabled=yes state=started
      with_items:
        - cif-router
        - cif-httpd
        - csirtg-smrt