---
- name: Install bearded-avenger
  hosts: localhost
  become: True
  roles:
    - { role: ubuntu14, tags: role-ubuntu14 }
    - { role: bearded-avenger, tags: role-bearded-avenger }

  post_tasks:
    - name: enable services at boot
      service: name={{ item }} enabled=yes state=started
      with_items:
        - cif-router
        - cif-httpd
        - csirtg-smrt
