---
- name: Install bearded-avenger
  hosts: localhost
  # http://docs.ansible.com/ansible/playbooks_environment.html
#  environment:
#    http_proxy: http://proxy.example.com:8080
  become: True
  roles:
    - { role: ubuntu14, tags: role-ubuntu14 }
    - { role: bearded-avenger, tags: role-bearded-avenger }

  post_tasks:

    - name: enable services at boot
      service: name={{ item }} enabled=yes state=started
      with_items:
        - cif-router
        - cif-httpd
        - csirtg-smrt