---
- name: Install bind9
  apt: pkg=bind9 state=installed update_cache=true cache_valid_time=86400
  notify: restart bind9

- name: "Setting named.conf.options"
  copy: src=bind_named.conf.options dest=/etc/bind/named.conf.options

- name: "Setting named.conf.local"
  copy: src=bind_named.conf.local dest=/etc/bind/named.conf.local

- name: "Setting dhclient.conf"
  copy: src=bind_dhclient.conf dest=/etc/dhcp/dhclient.conf

- name: "Setting /etc/resolvconf/resolv.conf.d/base"
  copy: src=bind_base dest=/etc/resolvconf/resolv.conf.d/base

#- name: "Restart networking"
#  command: bash -c "ifdown eth0 && ifup eth0"
