---
- name: Add apt HTTPS support
  apt: name=apt-transport-https state=present

- name: Add apt HTTPS support
  apt: name=ca-certificates state=present

- name: Add python repo
  apt_repository: repo='ppa:maxmind/ppa'

- name: Update apt cache if needed.
  apt: update_cache=yes cache_valid_time=3600 upgrade=yes

- name: install deps
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - build-essential
    - htop
    - git
    - python2.7
    - python-pytest
    - python-pip
    - python-dev
    - virtualenvwrapper
    - python-virtualenv
    - geoipupdate
    - libgeoip-dev
    - geoip-bin

- name: update pip
  command: easy_install -U pip
  become: yes

- name: update vex and requests
  pip: name="{{ item }}" extra_args="--upgrade"
  with_items: [ requests vex ] # requests first, old version conflicts with new pip

- name: install supervisord
  pip: name='supervisor==3.2.1'
