---
- name: test for setup.py
  find: paths=../../ patterns=setup.py
  register: p

- debug: msg={{ p }}

- name: set fact for configuring from source
  set_fact:
    CIF_SDIST: '1'
  when: p.matched == 1