- name: setup git
  shell: git config --global credential.helper store
  become: yes
  become_user: "{{ ansible.SUDO_USER }}"
  when: ansible.SUDO_USER is defined and ansible.SUDO_USER != ""

- name: setup git tokens
  shell: echo "https://{{ GH_TOKEN }}:x-oauth-basic@github.com" > ~/.git-credentials
  become: yes
  become_user: "{{ ansible.SUDO_USER }}"
  when: ansible.SUDO_USER is defined and ansible.SUDO_USER != ""