---
- include: github.yml
  tags: github
  when: GH_TOKEN != ""

- include: paths.yml
  tags: paths

- include: check_sdist.yml
  when: (CIF_SDIST is undefined or CIF_SDIST == "")

- include: dist.yml
  when: (CIF_SDIST is undefined or CIF_SDIST == "")
  tags: dist

- include: sdist.yml
  when: (CIF_SDIST is defined and CIF_SDIST == "1")
  tags: sdist

- include: rules.yml
  tags: rules

- include: tokens.yml
  tags: tokens