---
- name: Install bearded-avenger
  hosts: localhost
  become: True
  roles:
    - { role: centos7, tags: role-centos7 }
    - { role: bearded-avenger, tags: role-bearded-avenger }
  post_tasks:
    - name: start cif-services
      command: systemctl start {{ item }}
      with_items:
        - cif-router
        - cif-store
        - cif-httpd
        - cif-hunter
        - csirtg-smrt
