---
- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include: centos.yml
  when: ansible_distribution == "CentOS"

- name: setup ES dirs
  file: path={{ item }} state=directory mode=770
  with_items:
    - /mnt/elasticsearch/data
    - /mnt/elasticsearch/config
    - /mnt/elasticsearch/config/scripts

- name: copy ES configs
  copy: src={{ item }} dest=/mnt/elasticsearch/config mode=644
  with_items:
    - elasticsearch.yml
    - logging.yml

- name: pull recent docker image
  command: docker pull elasticsearch:{{ elasticsearch_version }}
  async: 300
  poll: 5

- name: start elasticsearch
  command: docker run -d --restart=always -p 9200:9200 -p 9300:9300 -v /mnt/elasticsearch/data:/usr/share/elasticsearch/data elasticsearch:{{ elasticsearch_version}} elasticsearch

- name: modify etc/default/cif with CIF_ES_NODES
  lineinfile: dest=/etc/default/cif line='export CIF_ES_NODES={{ elasticsearch_nodes }}'