---
# tasks file for elasticsearch
- name: Add docker key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Add docker repo
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present filename=docker

- name: Update apt cache if needed.
  apt: update_cache=yes

- name: install deps
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - linux-image-extra-virtual
    - docker-engine

- name: copy sysctl conf for vm.max_map_count
  template: src=sysctl_conf.j2 dest=/etc/sysctl.d/99-elasticsearch.conf mode=0660

- name: setting sysctl
  command: sysctl -w vm.max_map_count={{ elasticsearch_vm_max_map_count }}
