---
# tasks file for elasticsearch
- name: Add docker key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Add docker repo
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present filename=docker

- name: Update apt cache if needed.
  apt: update_cache=yes

- name: install deps
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - linux-image-extra-virtual
    - docker-engine

- name: setup ES dirs
  file: path={{ item }} state=directory mode=770
  with_items:
    - /mnt/elasticsearch/data
    - /mnt/elasticsearch/config
    - /mnt/elasticsearch/config/scripts

- name: copy ES configs
  copy: src={{ item }} dest=/mnt/elasticsearch/config mode=644
  with_items:
    - elasticsearch.yml
    - logging.yml

- name: copy sysctl conf for vm.max_map_count
  template: src=sysctl_conf.j2 dest=/etc/sysctl.d/99-elasticsearch.conf mode=0660

- name: setting sysctl
  command: sysctl -w vm.max_map_count={{ elasticsearch_vm_max_map_count }}

- name: pull recent docker image
  command: docker pull elasticsearch:{{ elasticsearch_version }}
  async: 300
  poll: 5

- name: start elasticsearch
  command: docker run -d --restart=always -p 9200:9200 -p 9300:9300 -v /mnt/elasticsearch/data:/usr/share/elasticsearch/data elasticsearch:{{ elasticsearch_version}} elasticsearch

- name: modify etc/default/cif with CIF_ES_NODES
  lineinfile: dest=/etc/default/cif line='export CIF_ES_NODES={{ elasticsearch_nodes }}'