---
- name: create /etc/geopip.conf
  template: src=GeoIP.conf.j2 dest=/etc/GeoIP.conf owner=root group=root mode=0660

- name: create GeoIP path /usr/local/share/GeoIP
  file: path=/usr/local/share/GeoIP state=directory owner=root group=root mode=0755

- name: update geoip databases
  command: geoipupdate -v

- name: create geoip update cron
  cron: name="geoip update" user="root" job="/usr/bin/geoipupdate"
        cron_file=geoipupdate day=01