---
- name: copy init scripts
  copy: src="{{ item }}" dest="/etc/init.d/{{ item }}" mode=0755 backup=yes
  with_items:
    - cif-router
    - csirtg-smrt
    - cif-httpd
    - cif-services

- name: enable services at boot
  service: name=cif-services enabled=yes

- name: copy supervisord configs
  copy: src="{{ item }}" dest=/etc/cif/ mode=0660 owner="{{ app_user }}" group="{{ app_user }}"
  with_items:
    - cif-router.conf
    - cif-httpd.conf
    - csirtg-smrt.conf

- name: copy /etc/defaults/cif
  template: src=defaults.j2 dest=/etc/default/cif mode=0660 owner="{{ app_user }}" group="{{ app_user }}"

- name: configure /etc/security/limits.conf
  lineinfile: dest=/etc/security/limits.conf line="cif             soft    nofile            20000"

- name: configure /etc/security/limits.conf
  lineinfile: dest=/etc/security/limits.conf line="cif             hard    nofile            30000"
