---
- name: Install bind9
  yum: pkg=bind state=installed

- name: "Setting named.conf"
  copy: src=bind_named.conf dest=/etc/named.conf

- name: restart named
  command: systemctl restart named

- name: enable named
  command: systemctl enable named

- name: update NetworkManager.conf
  copy: src=NetworkManager.conf dest=/etc/NetworkManager/NetworkManager.conf

- name: restart NetworkManager
  command: systemctl restart NetworkManager

- name: "Restart networking"
  command: systemctl restart network

- name: copy resolv.conf
  copy: src=named_resolv.conf dest=/etc/resolv.conf