---
- name: install EPEL
  yum: name=epel-release state=latest

- name: install deps
  yum:
    state: present
    pkg: "{{ item }}"
  with_items:
    - htop
    - git
    - "@Development Tools"
    - openssl-devel
    - sqlite-devel
    - bzip2-devel
    - python-virtualenvwrapper
    - bind-utils
    - libxml2-python
    - libxml2-devel
    - libxslt
    - libxslt-devel
    - libcurl-devel
    - net-tools
    - wget