---
- name: install EPEL
  yum: name=epel-release state=latest

- name: install deps
  yum:
    state: present
    pkg: "{{ item }}"
  with_items:
    - htop
    - git
    - "@Development Tools"
    - openssl-devel
    - sqlite-devel
    - bzip2-devel
    - python-virtualenvwrapper
    - bind-utils
    - libxml2-python
    - libxml2-devel
    - libxslt
    - libxslt-devel
    - libcurl-devel
    - net-tools
    - wget

- name: install pyopenssl for python 2.7.6
  pip: name='pyopenssl==16.2.0'

- name: update openssl deps
  pip: name="{{ item }}" extra_args="--upgrade"
  with_items: [ pyasn1 ndg-httpsclient ]