---
- name: create geoip update cron
  cron: name="geoip update" user="root" job="/usr/bin/geoipupdate"
        cron_file=geoipupdate day=01

- name: create /etc/GeoIP.conf
  template: src=GeoIP.conf.j2 dest=/etc/GeoIP.conf owner=root group=root mode=0660

- name: update geoip databases
  command: geoipupdate -v