---
- name: create sandbox directory
  file: path={{ python_tmp }} state=directory

- name: download source tarballs
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  with_items:
    - url: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz"
      dest: "{{ python_tmp }}"
    - url: https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py
      dest: "{{ python_tmp }}"
    - url: https://raw.githubusercontent.com/pypa/pip/master/contrib/get-pip.py
      dest: "{{ python_tmp }}"

- name: unarchive tarballs
  unarchive:
    copy: no
    src: "{{ python_tmp }}/{{ item }}"
    dest: "{{ python_tmp }}"
  with_items:
    - Python-{{ python_version }}.tgz

- name: configure python
  command: ./configure --prefix=/usr/local --enable-unicode=ucs2 chdir="{{ python_tmp }}/Python-{{ python_version }}"

- name: make python
  command: make chdir="{{ python_tmp }}/Python-{{ python_version }}"

- name: install python
  command: make install chdir="{{ python_tmp }}/Python-{{ python_version }}"

- name: install ez_setup
  command: /usr/local/bin/python2.7 ./ez_setup.py chdir="{{ python_tmp }}"

- name: install pip
  command: /usr/local/bin/python2.7 ./get-pip.py chdir="{{ python_tmp }}"

- name: symlink python2.7
  file: src=/usr/local/bin/python2.7 dest=/usr/local/bin/python state=link force=yes

- name: symlink pip
  file: src=/usr/local/bin/pip dest=/usr/bin/pip state=link force=yes

- name: Ensure vagrant user has a .profile
  file:
    path: "/home/{{ ansible_env.SUDO_USER }}/.profile"
    state: touch
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0660

- name: Add vars to app env
  lineinfile: dest="/home/{{ ansible_env.SUDO_USER }}/.bash_profile" line="export PATH=/usr/local/bin:$PATH"