# https://semaphoreci.com/community/tutorials/testing-ansible-roles-on-multiple-operating-systems-with-docker-and-semaphore
---
- name: systemd env file
  template: src=cif.env.j2 dest=/etc/cif.env owner=cif group=cif mode=0660
  tags: configuration

- name: systemd services
  copy: src={{ item }} dest=/etc/systemd/system owner=root group=root mode=0644
  tags: configuration
  with_items:
    - cif-router.service
    - cif-httpd.service
    - csirtg-smrt.service
  notify:
    - reload systemd

- name: enable services at boot
  service: name={{ item }} enabled=yes
  with_items:
    - cif-router.service
    - cif-httpd.service
    - csirtg-smrt.service