---
- name: Install bearded-avenger with elasticsearch (using Docker)
  hosts: localhost
  become: True
  environment:
    http_proxy: http://proxy.tkagit.com:8080
    https_proxy: http://proxy.tkagit.com:8080
    LANG: C
    LC_ALL: C
    LC_MESSAGES: C
  vars:
    - cif_store_store: 'elasticsearch'
  roles:
    - { role: ubuntu16, tags: role-ubuntu16 }
    - { role: elasticsearch, tags: role-elasticsearch }
    - { role: bearded-avenger, tags: role-bearded-avenger }

  post_tasks:
    - name: enable services at boot
      service: name={{ item }} enabled=yes state=started
      with_items:
        - cif-router
        - cif-httpd
        - csirtg-smrt
