# http://docs.ansible.com/ansible/playbooks_environment.html
# environment:
#   http_proxy: http://proxy.example.com:8080
---
- name: configure platform
  hosts: all
  gather_facts: False
  become: True

  vars_files:
    - "../global_vars.yml"

  vars:
    CIF_ES: "{{ lookup('env', 'ANSIBLE_CIF_ES') }}"
    GH_TOKEN: "{{ lookup('env', 'GH_TOKEN' }}"
    CIF_SDIST: "{{ lookup('env', 'CIF_ANSIBLE_SDIST') }}"

  pre_tasks:

    - name: configure python
      raw: sudo apt-get install python-minimal aptitude -y

    - setup:
       filter: ansible_*

    - name: set store fact
      set_fact:
        cif_store_store: 'elasticsearch'
      when: CIF_ES == "1"

    - debug: msg="Configuring with ElasticSearch"
      when: CIF_ES == "1"

    - debug: msg="Configuring with SDIST"
      when: CIF_SDIST == "1"

  roles:
    - { role: ubuntu16, tags: role-ubuntu16 }
    - { role: elasticsearch, tags: role-elasticsearch, when: CIF_ES == "1" }
    - { role: bearded-avenger, tags: role-bearded-avenger }

  post_tasks:

    - name: enable services at boot
      service: name={{ item }} enabled=yes state=started
      with_items:
        - cif-router
        - cif-httpd
        - csirtg-smrt