---
- name: Install bearded-avenger
  hosts: cif
    # http://docs.ansible.com/ansible/playbooks_environment.html
#  environment:
#    http_proxy: http://proxy.example.com:8080
  sudo: true
  roles:
    - { role: ubuntu14, tags: role-ubuntu14 }
    - { role: bearded-avenger, tags: role-bearded-avenger }
