---
- name: Install bearded-avenger
  hosts: localhost
  become: true
  vars:
    GH_TOKEN: "{{ lookup('env', 'GH_TOKEN') }}"
    ci: true
    app_user: travis
  roles:
    - { role: ubuntu14, tags: role-ubuntu14 }
    - { role: bearded-avenger, tags: role-bearded-avenger }
