---
# handlers file for centos71-check
- name: restart firewall
  command: service firewall restart

- name: reload systemd
  command: systemctl daemon-reload

- name: restart named
  command: systemctl reload named